### ISSUE TITLE
Sincerely for detailed steps

### ISSUE THREAD

**Issue by lihuaqingliii** [Luchixiang/PCRL#11]
Deeply attracted by the content of your paper.Could you please list the detailed steps of running the code?Thank you very much!

**Comment by Luchixiang** [comment]
We have listed the steps of running our code in the README. Please let me know which part you don't know how to run.

**Comment by lihuaqingliii** [comment]
Sorry, I thought you ware going to list the steps of finetuning in addition to the pre-training steps.

I am sorry to disturb you.Best wishes.

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Luchixiang/PCRL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月3日(星期二) 晚上7:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Luchixiang/PCRL] Sincerely for detailed steps (Issue #11)





 
We have listed the steps of running our code in the README. Please let me know which part you don't know how to run.
