### ISSUE TITLE
请问一下luna_pre中这段的作用是什么？想按照luna_pre处理一下自己的数据集

### ISSUE THREAD

**Issue by li-pengcheng** [Luchixiang/PCRL#2]
t_img1 = np.zeros((input_rows, input_cols, input_depth), dtype=float)
        d_img1 = np.zeros((input_rows, input_cols, input_depth), dtype=float)
        t_img2 = np.zeros((input_rows, input_cols, input_depth), dtype=float)
        d_img2 = np.zeros((input_rows, input_cols, input_depth), dtype=float)
        for d in range(input_depth):
            for i in range(input_rows):
                for j in range(input_cols):
                    for k in range(config.len_depth):
                        if crop_window1[i, j, d + k] >= config.HU_thred:
                            t_img1[i, j, d] = crop_window1[i, j, d + k]
                            d_img1[i, j, d] = k
                            break
                        if k == config.len_depth - 1:
                            d_img1[i, j, d] = k
        for d in range(input_depth):
            for i in range(input_rows):
                for j in range(input_cols):
                    for k in range(config.len_depth):
                        if crop_window2[i, j, d + k] >= config.HU_thred:
                            t_img2[i, j, d] = crop_window2[i, j, d + k]
                            d_img2[i, j, d] = k
                            break
                        if k == config.len_depth - 1:
                            d_img2[i, j, d] = k

        d_img1 = d_img1.astype('float32')
        d_img1 /= (config.len_depth - 1)
        d_img1 = 1.0 - d_img1
        d_img2 = d_img2.astype('float32')
        d_img2 /= (config.len_depth - 1)
        d_img2 = 1.0 - d_img2

        if np.sum(d_img1) > config.lung_max * crop_deps1 * crop_rows1 * crop_cols1:
            continue
        # print(np.sum(d_img1))
        if np.sum(d_img2) > config.lung_max * crop_deps2 * crop_rows2 * crop_cols2:
            continue
        return crop_window1[:, :, :input_depth], crop_window2[:, :, :input_depth]

**Comment by Luchixiang** [comment]
你好，这部分代码主要是用来确保crop出来的图像包含足够多的肺器官信息，而不是绝大多数都是背景信息。因为只有背景信息的图像对预训练来说是没用的。
