### ISSUE TITLE
请教几个问题

### ISSUE THREAD

**Issue by xiaocheng2333** [Luchixiang/PCRL#4]
[
![image](https://user-images.githubusercontent.com/62132324/139219752-00eae385-fbee-4ffb-83da-e446906095c0.png)
](url)
[
![image](https://user-images.githubusercontent.com/62132324/139220703-11c35a37-98fe-4d78-83c6-91cff6b7b72e.png)
](url)

您好～还有几个问题：

1. 代码里Transformation-conditioned Attention module是去掉了outer product，只剩下右边的channel-wise multiplication了么
2. 在代码里面好像没有见到feat_k和mask2的MSEloss
3. 想问下您有测试代码吗

打扰了，非常感谢！

**Comment by Luchixiang** [comment]
1. 是的
2. 为了节省gpu内存 我们在代码中删掉了这个mse,你也可以在计算mse_loss的时候加上去
3. 测试代码你可以根据需要的数据集去网上找，用的都是比较常用的数据集，网上也都有相关代码的，如果你依然有疑惑，我们可以给你提供相关数据集的测试代码
