### ISSUE TITLE
关于’chest_train.txt‘中的数字的问题

### ISSUE THREAD

**Issue by HardworkingLittlequ** [Luchixiang/PCRL#5]
您好！谢谢您能将这篇工作的代码开源，这篇工作非常启发我！但是有几个小问题想请教一下。我将您文章中使用的chest数据集改为了自己的二维数据集，但是我不知道chest_train.txt是如何生成的，请问图像名称后类似 "0 0 0 0 0 0 1 0 0 1 0 1 0 0"的label是如何生成的呢，如果我使用自己的数据集，该如何生成呢？谢谢！

**Comment by Luchixiang** [comment]
这个是chest的class label,只在finetune的时候会用到，预训练的时候并不会用到，只需要把它换成你数据集中图片对应的class label就行

**Comment by HardworkingLittlequ** [comment]
> 这个是chest的class label,只在finetune的时候会用到，预训练的时候并不会用到，只需要把它换成你数据集中图片对应的class label就行

明白了！谢谢！

**Comment by HardworkingLittlequ** [comment]
您好！抱歉打扰，还有个关于您PCRL文章的小问题想请教您。请问您文章中fintuning时使用的是哪一部分的特征？我看您在github上没有放测试和fintuning的代码，请问可以提供一下吗。我对您的这项研究非常感兴趣，也学习到很多。 祝您身体健康、科研顺利！ lhqu20 ***@***.*** 签名由 网易邮箱大师 定制 在2021年11月12日 23:15，Luchixiang 写道： 这个是chest的class label,只在finetune的时候会用到，预训练的时候并不会用到，只需要把它换成你数据集中图片对应的class label就行 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Luchixiang** [comment]
感谢您的关注！ finetune的代码可以直接在网上找相关数据集的finetune代码，用的都是比较常见的数据集，很容易能够找到。就是将预训练好的模型在finetune开始的时候加载进去就行（类似imagenet）
