### ISSUE TITLE
regarding luna preprocessing

### ISSUE THREAD

**Issue by ananyajana** [Luchixiang/PCRL#6]
there is a check in the luna preprocessing 
if np.sum(d_img1) > config.lung_max * crop_deps1 * crop_rows1 * crop_cols1:

the size of d_img is input_rows, input_cols, input_depth which is 64x64x32
but it is being checked against a cube of size crop_deps1 * crop_rows1 * crop_cols1

these two could be different as there are options to choose i.e.
col_size = [(64, 64, 32), (96, 96, 48), (96, 96, 96), (32, 32, 16), (112, 112, 64)]

so when the cube size is (32, 32, 16) there is a chance that the np.sum(d_img1) is always greater than config.lung_max * crop_deps1 * crop_rows1 * crop_cols1 and hence don't get selected

so the chances of selecting cubes of (32, 32,, 16) might actually be less?

**Comment by Luchixiang** [comment]
Yes. I mean in the pretraining stage, we want our model to see more and learn more. You can change np.sum(d_img1) > config.lung_max * crop_deps1 * crop_rows1 * crop_cols1: into
np.sum(d_img1) > config.lung_max * input_deps * input_rows * input_cols if you want to treat each size equally.

**Comment by ananyajana** [comment]
@Luchixiang thank you for your quick response, appreciate it!
