### ISSUE TITLE
query regarding downstream task data pre-processing

### ISSUE THREAD

**Issue by ananyajana** [Luchixiang/PCRL#7]
Hi Luchixiang,

Hope you are doing great. I have a question regarding the downstream task data pre-processing. Exactly which operation is performed on the 3D LUNA, 3D Brats and 3D LiTs volumes and the segmentation mask volumes? Are they resized or Are they resampled? which function do you use i.e. SimpleITK resample or skimage rescale or just array resizing?
I assume that for the downstream tasks, all the volumes are resized to 64x64x32?

Thanks,
Ananya

**Comment by Luchixiang** [comment]
For downstream tasks, you should perform different preprocessing strategies. They are both resized using skimage. And you can adjust the input size in different tasks.  For luna classification, our input size is (48,48,48) and they are extracted from the official candidates. For Brats segmentation, our input size is (64,64,64) with only resampling preprocessing.
